import { Banner } from '@/app/partials/Banner';
import { Container } from '@/components';



import { GalleryList } from './components/gallery-list';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'درگاه داده باز - سامانه وفا',
    description: 'Generated by create next app'
};



export const dynamic = 'force-dynamic';

export default function OpenDataPage() {
   return (
      <>
         <Banner className='py-24'>
            <h1 className=''>{'درگاه داده باز'}</h1>
            <p className='mt-6 mb-6 text-center md:mt-7 lg:mt-8'>
               {'در این بخش می‌توانید اطلاعات کاملی از عملکرد وزارت فرهنگ و ارشاد اسلامی بدست آورید.'}
            </p>
         </Banner>
         <Container>
            <GalleryList />
         </Container>
      </>
   );
}
