import type {Metadata} from "next";
import {Vazirmatn} from "next/font/google";
import "./globals.css";
import {LayoutHeader} from "@/app/partials/header";
import {LayoutFooter} from "@/app/partials/footer";
import ThemeChangerProvider from "@/app/partials/theme-changer-provider";


const vazirMatn = Vazirmatn({
    variable: "--vazir-mat",

});


export const metadata: Metadata = {
    title: 'صفحه نخست - سامانه وفا',
    description: 'Generated by create next app'
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir={'rtl'}>
        <body className={`${vazirMatn.className} antialiased bg-slate-100 dark:bg-zinc-800 text-zinc-950 dark:text-zinc-50`}>
            <ThemeChangerProvider position="right">
                <div className="outer-container">
                    <LayoutHeader/>
                    <main className="min-h-svh">
                        {children}
                    </main>
                    <LayoutFooter/>
                </div>
            </ThemeChangerProvider>
        </body>
        </html>
    );
}
