import type {Metadata} from "next";
import {Vazirmatn} from "next/font/google";
import "./globals.css";
import {LayoutHeader} from "@/app/partials/header";
import {LayoutFooter} from "@/app/partials/footer";


const vazirMatn = Vazirmatn({
    variable: "--vazir-mat",
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir={'rtl'}>
        <body className={`${vazirMatn.className} antialiased outer-container`}>
        <LayoutHeader/>
        <main className="min-h-svh">
            {children}
        </main>
        <LayoutFooter/>
        </body>
        </html>
    );
}
