import type { ReactNode } from 'react';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { ThemeProvider } from 'next-themes';

import '@/app/globals.css';

import { Footer, Header } from './partials';
import ThemeChangerProvider from './partials/theme-changer-provider';





export const metadata: Metadata = {
   title: 'صفحه نخست - سامانه وفا',
   description: 'Generated by create next app'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
   return (
      <html suppressHydrationWarning lang='fa'>
         <body className={`bg-background text-foreground flex min-h-screen flex-col antialiased`}>
            <ThemeProvider attribute='class'>
               <ThemeChangerProvider position="right">
               <Header />
               <main className='flex-1'>
                 {children}
                  </main>
               <Footer />
               </ThemeChangerProvider>
            </ThemeProvider>
         </body>
      </html>
   );
};

export default Layout;
