import { Container } from '@/components';
import { fetchLicensesData } from '@/lib/fetch-license';

import { NormalizedDataProvider } from './components/gallery';
import { GalleryList } from './components/gallery/gallery-list';
import { Hero } from '@/app/service-desk/components/hero';
import type { Metadata } from 'next';

// 1. Force static render for SEO
export const dynamic = 'force-dynamic';
// 2. ISR: revalidate every hour
// export const revalidate = 3600;
export const metadata: Metadata = {
   title: 'درگاه مجوزها - سامانه وفا',
   description: 'Generated by create next app'
};

export default async function ServiceDeskPage(props: {
   searchParams?: Promise<{
      q?: string;
   }>;
}) {
   const data = await fetchLicensesData();

   return (
      <NormalizedDataProvider normalizedData={data}>
         <Hero />
         <Container>
            <GalleryList />
         </Container>
      </NormalizedDataProvider>
   );
}
