import { Banner } from '@/app/partials/Banner';
import { Container } from '@/components';

import { GalleryList } from './components/gallery-list';
import { GalleryList2 } from './components/gallery-list-2';
import type { Metadata } from 'next';

export const dynamic = 'force-dynamic';
export const metadata: Metadata = {
   title: 'درگاه شفافیت - سامانه وفا',
   description: 'Generated by create next app'
};
export default function TransparencyPage() {
   return (
      <>
         <Banner className='mb-12 py-24'>
            <h1 className=''>{'درگاه شفافیت'}</h1>
            <p className='mt-6 mb-6 text-center md:mt-7 lg:mt-8'>
               {'در این بخش می‌توانید اطلاعات کاملی از عملکرد وزارت فرهنگ و ارشاد اسلامی بدست آورید.'}
            </p>
         </Banner>
         <Container>
            <GalleryList2 />
         </Container>
      </>
   );
}
